const students = [
  {
    id: "6712040",
    name: "James Brown",
    participation: 0,
    quiz: 0,
    midterm: 0,
    final: 0,
    project1: 0,
    project2: 0,
  },
  {
    id: "6712041",
    name: "Emily Davis",
    participation: 0,
    quiz: 0,
    midterm: 0,
    final: 0,
    project1: 0,
    project2: 0,
  },
  {
    id: "6712042",
    name: "Michael Johnson",
    participation: 0,
    quiz: 0,
    midterm: 0,
    final: 0,
    project1: 0,
    project2: 0,
  },
  {
    id: "6712043",
    name: "Sarah Wilson",
    participation: 0,
    quiz: 0,
    midterm: 0,
    final: 0,
    project1: 0,
    project2: 0,
  },
  {
    id: "6712044",
    name: "David Martinez",
    participation: 0,
    quiz: 0,
    midterm: 0,
    final: 0,
    project1: 0,
    project2: 0,
  },
  {
    id: "6712045",
    name: "Jessica Taylor",
    participation: 0,
    quiz: 0,
    midterm: 0,
    final: 0,
    project1: 0,
    project2: 0,
  },
  {
    id: "6712046",
    name: "Christopher Anderson",
    participation: 0,
    quiz: 0,
    midterm: 0,
    final: 0,
    project1: 0,
    project2: 0,
  },
  {
    id: "6712047",
    name: "Amanda Thomas",
    participation: 0,
    quiz: 0,
    midterm: 0,
    final: 0,
    project1: 0,
    project2: 0,
  },
  {
    id: "6712048",
    name: "Daniel Jackson",
    participation: 0,
    quiz: 0,
    midterm: 0,
    final: 0,
    project1: 0,
    project2: 0,
  },
  {
    id: "6712049",
    name: "Olivia White",
    participation: 0,
    quiz: 0,
    midterm: 0,
    final: 0,
    project1: 0,
    project2: 0,
  },
];
